stages:
  - test

lint:
  stage: test
  image: node
  script:
    - npm install
    - npm run build
    - npm run lint

jest:
  stage: test
  image: node
  script:
    - npm install
    - npm run build
    - npm run test

