stages:
  - test

variables:
  PYTHON_VERSION: "3"

njsscan:
  stage: test
  before_script:
    - apt update -qy
    - apt install -y python${PYTHON_VERSION} python3-pip
    - apt install -y python3.11-venv
    - python3 -m venv .venv
    - source .venv/bin/activate
    - python3 -m pip install njsscan
  script:
    - pwd
    - ls
    - njsscan .
  only:
    - merge_requests
  tags:
    - linrunner

lint:
  stage: test
  script:
    - npm install
    - npm run build
    - npm run lint
  only:
    - merge_requests
  tags:
    - linrunner
