stages:
  - test

njsscan:
  stage: test
  before_script:
    - pip3 install --upgrade njsscan
  script:
    - njsscan .
  only:
    - merge_requests
  tags:
    - linrunner

lint:
  stage: test
  script:
    - npm install
    - npm build
    - npm run lint
  only:
    - merge_requests
  tags:
    - linrunner
