stages:
  - test

variables:
  QEMU_IMAGE: "multiarch/qemu-user-static"
  NJSSCAN_IMAGE: "opensecurity/njsscan:latest"
  SOURCE_DIR: "/."

run_x86_container:
  stage: test
  image: $QEMU_IMAGE
  script:
    - docker pull $NJSSCAN_IMAGE
    - docker run -v $(pwd):$SOURCE_DIR --platform linux/amd64 -it $NJSSCAN_IMAGE $SOURCE_DIR
  only:
    - merge_requests
  tags:
    - linrunner
lint:
  stage: test
  image: node
  script:
    - npm install
    - npm run build
    - npm run lint
  only:
    - merge_requests
  tags:
    - linrunner
