stages:
  - test

njsscan:
  stage: test
  image: opensecurity/njsscan
  before_script:
      - pwd
  script:
      - njsscan .
  only:
    - merge_requests
  tags:
    - linrunner

lint:
  stage: test
  image: node
  script:
    - npm install
    - npm run build
    - npm run lint
  only:
    - merge_requests
  tags:
    - linrunner
